### PR TITLE
Toolchain/ptrees

### LINKED ISSUE #1: Better integration of ptrees in the build process
The problem is than we currently need to compile *ptrees* separately while we would like this to be automatically done during Javalib build.
Moreover, we want to stop altering the **opam** user repository with `ocamlfind install ptrees`, especially since our versions of *ptmap* and *ptset* are modified versions of the original ones distributed with **opam**.

### PR DESCRIPTION
**Pull request by anscoil**
I moved the directory _ptrees_ into _src_.
The _Makefile_ files and _configure.sh_ have been modified accordingly.
Everything compiles, and some basic tests (not yet under version control) succeed after `make install` of __Javalib__.

This fixes #1.

### CODE REVIEW

**Review by davidpichardie — CHANGES_REQUESTED** [review]
I think src/ptrees/Makefile could be remove if you strengthen MODULES and MODULE_INTERFACES with ptrees files (with right prefix).
The FOR_PACK variable could stay in src/Makefile
File ptrees/META is not used anymore

**Comment by anscoil** [comment]
I made the modifications. Are we ready to merge ?

**Review by davidpichardie — APPROVED** [review]
Looks good!

**Comment by davidpichardie** [comment]
I let you push the "Merge pull request" magic button!

**Pull request merged**
